SET GLOBAL log_bin_trust_function_creators = 1;

CREATE TABLE IF NOT EXISTS companyStatus (
    statusId CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    status VARCHAR(50) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO companyStatus (statusId, status) VALUES ("c0246355-2708-11f0-9bf9-0242ac130002", "active");
INSERT INTO companyStatus (status) VALUES ("inactive");

CREATE TABLE IF NOT EXISTS currency (
    currencyId CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    symbol VARCHAR(10) NOT NULL,
    country VARCHAR(100) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO currency (symbol, country) VALUES ('R$', 'BR');
INSERT INTO currency (symbol, country) VALUES ('$', 'US');

CREATE TABLE IF NOT EXISTS dateFormat (
    dateFormatId CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    dateFormat VARCHAR(10) NOT NULL,
    country VARCHAR(2) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO dateFormat (dateFormat, country) VALUES ('DD/MM/YYYY', "BR");
INSERT INTO dateFormat (dateFormat, country) VALUES ('MM/DD/YYYY', "US");

CREATE TABLE IF NOT EXISTS ambient (
    ambientId CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    name VARCHAR(100) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS company (
    companyId CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    name VARCHAR(100) NOT NULL,
    statusId CHAR(36) NOT NULL,
    currencyId CHAR(36) NOT NULL,
    dateFormatId CHAR(36) NOT NULL,
    ambientId CHAR(36) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (statusId) REFERENCES companyStatus(statusId),
    FOREIGN KEY (currencyId) REFERENCES currency(currencyId),
    FOREIGN KEY (dateFormatId) REFERENCES dateFormat(dateFormatId),
    FOREIGN KEY (ambientId) REFERENCES ambient(ambientId),
    UNIQUE KEY (name, ambientId)
);

CREATE TABLE IF NOT EXISTS user (
    userId CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    profilePicture VARCHAR(255),
    lastLogin TIMESTAMP NULL,
    lastAmbientId CHAR(36) NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS userCompany (
    userCompanyId CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    userId CHAR(36) NOT NULL,
    companyId CHAR(36) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES user(userId),
    FOREIGN KEY (companyId) REFERENCES company(companyId),
    UNIQUE KEY (userId, companyId)
);

CREATE TABLE IF NOT EXISTS eventStatus (
    statusId CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    status VARCHAR(50) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO eventStatus (statusId, status) VALUES ("3fc5627a-2127-4cfb-a94f-e47f4d5ec77d", "active");
INSERT INTO eventStatus (status) VALUES ("inactive");

CREATE TABLE IF NOT EXISTS event (
    eventId CHAR(36) PRIMARY KEY DEFAULT (UUID()),
    name VARCHAR(100) NOT NULL,
    statusId CHAR(36) NOT NULL,
    startDate DATETIME NOT NULL,
    endDate DATETIME NOT NULL,
    companyId CHAR(36) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (statusId) REFERENCES eventStatus(statusId),
    FOREIGN KEY (companyId) REFERENCES company(companyId),
    UNIQUE KEY (name, companyId)
);
